CREATE TABLE app_user
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subject VARCHAR(255) NOT NULL,

    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uk_app_user_subject UNIQUE (subject)
);

CREATE TABLE deadline
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title      VARCHAR(255),
    course     VARCHAR(255),
    due_date   TIMESTAMP WITHOUT TIME ZONE,
    type       VARCHAR(255),
    difficulty VARCHAR(255),
    notes      VARCHAR(1000),
    user_id    BIGINT,

    CONSTRAINT pk_deadline PRIMARY KEY (id),

    CONSTRAINT fk_deadline_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE
);

CREATE TABLE revision_task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255),
    completed   BOOLEAN NOT NULL DEFAULT FALSE,
    deadline_id BIGINT,

    CONSTRAINT pk_revision_task PRIMARY KEY (id),

    CONSTRAINT fk_revision_task_deadline
        FOREIGN KEY (deadline_id)
            REFERENCES deadline (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_deadline_user_id
    ON deadline (user_id);

CREATE INDEX idx_revision_task_deadline_id
    ON revision_task (deadline_id);